Make some improvements and fixes.

diff --git a/git-hooks/bootc-projects/post-receive b/git-hooks/bootc-projects/post-receive
--- a/git-hooks/bootc-projects/post-receive
+++ b/git-hooks/bootc-projects/post-receive
@@ -2,8 +2,12 @@
 
 # SPDX-License-Identifier: GPL-2.0
 
-PROJECT=
-BUILD-ID=CI-$(date -u +%Y%m%d%H%M)
+PROJECT=""
+
+if [[ $PROJECT = "" ]]; then
+	echo "Missing project name in git hook!"
+	exit 1
+fi
 
 # the work tree, where the checkout/deploy should happen
 NIGHTLY_WORKDIR="$HOME/ci-build/${PROJECT}-nightly"
@@ -25,6 +29,7 @@ while read oldrev newrev ref; do
 	if [ -x ${SCRIPT} ]; then
 		if [ "$ref" = "refs/heads/${BRANCH}" ]; then
 			if [ ! -f ${LOCK_NIGHTLY} ]; then
+				BUILD_ID="NIG-$(date -u +%Y%m%d%H%M)"
 				echo "Ref $ref received. Building \"nightly\" image."
 
 				if [ ! -d ${NIGHTLY_WORKDIR} ]; then
@@ -33,13 +38,14 @@ while read oldrev newrev ref; do
 
 				rm -rf "${NIGHTLY_WORKDIR}/*"
 				git --work-tree="${NIGHTLY_WORKDIR}" --git-dir="${GIT_DIR}" checkout -f ${BRANCH}
-				(setsid bash ${SCRIPT} ${PROJECT} ${NIGHTLY_WORKDIR} nightly ${BUILDID} </dev/null &>/dev/null &) &
+				(setsid bash ${SCRIPT} ${PROJECT} ${NIGHTLY_WORKDIR} nightly ${BUILD_ID} </dev/null &>/dev/null &) &
 			else
 				echo "Build is already running. Ignoring request."
 			fi
 
 		elif [[ "0000000000000000000000000000000000000000" == $oldrev ]] && [[ $ref == refs\/tags\/v* ]]; then
 			if [ ! -f ${LOCK_RELEASE} ]; then
+				BUILD_ID="REL-$(date -u +%Y%m%d%H%M)"
 				echo "Received new release tag $ref. Building stable image."
 
 				if [ ! -d ${RELEASE_WORKDIR} ]; then
@@ -48,7 +54,7 @@ while read oldrev newrev ref; do
 
 				rm -rf "${RELEASE_WORKDIR}/*"
 				git --work-tree="${RELEASE_WORKDIR}" --git-dir="${GIT_DIR}" checkout -f $ref
-				(setsid bash ${SCRIPT} ${PROJECT} ${RELEASE_WORKDIR} stable ${BUILDID} </dev/null &>/dev/null &) &
+				(setsid bash ${SCRIPT} ${PROJECT} ${RELEASE_WORKDIR} stable ${BUILD_ID} </dev/null &>/dev/null &) &
 			else
 				echo "Build is already running. Ignoring request."
 			fi
