Always pull the base images.

diff --git a/ci/bootc/bootc-build b/ci/bootc/bootc-build
--- a/ci/bootc/bootc-build
+++ b/ci/bootc/bootc-build
@@ -11,26 +11,12 @@ while getopts "p:w:t:b:uh" flag; do
 		t) TARGET=$OPTARG ;;
 		u) UPLOAD="true" ;;
 		h) help ;;
-		*)
-			echo 'Unknown option.'
-			exit 1
-			;;
+		*) echo 'Unknown option.' && help ;;
 	esac
 done
 
-# Database file
-DBFILE="$HOME/.ci/database/ci-reports.sqlite3"
-
-# Clean up if SIGINT occurs
-cleanup()
-{
-	trap SIGINT
-	rm -f $HOME/.ci/${PROJECT}/.$TARGET-running
-}
-
 # Print a hopefully useful help text.
-help()
-{
+help() {
 	cat << EOF
 Usage:
 bootc-build -p <project> -w <working-dir> -b <build-id> -t <target> [-u]
@@ -46,14 +32,22 @@ EOF
 	exit 1
 }
 
-# Trap interrupt signal
-trap "cleanup" INT
-
 # Show help if a mandatory option is missing
 if [ -z "$PROJECT" ] || [ -z "$BUILD_ID" ] || [ -z "$WORKDIR" ] \
 	|| [ -z "$TARGET" ]; then
 	help
 fi
+
+# Database file
+DBFILE="$HOME/.ci/database/ci-reports.sqlite3"
+
+# Clean up if SIGINT occurs
+cleanup() {
+	rm -f $HOME/.ci/${PROJECT}/.$TARGET-running
+}
+
+# Trap interrupt signal
+trap "cleanup; exit 1" INT
 
 # Initialize status variables
 MANIFEST=0
@@ -61,70 +55,65 @@ BUILD=0
 PUSH=0
 SUCCESS=0
 
-# Check if the triggered build is supportet to avoid dead images
-if [ "$TARGET" == "nightly" ] || [ "$TARGET" == "stable" ]; then
-	# Check if the desired build is already running
-	if [ ! -f $HOME/.ci/${PROJECT}/.$TARGET-running ]; then
-		# No buid running, so: ABRAKADABRA!
-		if [ ! -d $HOME/.ci/${PROJECT} ]; then
-			mkdir -p $HOME/.ci/${PROJECT}
-		fi
+# Check if the triggered build is supported to avoid dead images
+if [ "$TARGET" != "nightly" ] && [ "$TARGET" != "stable" ]; then
+	echo "Target must be 'nightly' or 'stable'." && exit 1
+fi
 
-		# Lock the build to avoid concurrent builds of the same type.
-		touch $HOME/.ci/${PROJECT}/.$TARGET-running
-
-		# Remove manifest if it exists
-		podman manifest rm dirk1980/${PROJECT}:$TARGET
-
-		# Create the manifest
-		podman manifest create -a dirk1980/${PROJECT}:$TARGET
-		if [ $? -eq 0 ]; then MANIFEST=1; fi
-
-		podman build --build-arg buildid=${BUILD_ID} \
-			--platform linux/amd64,linux/arm64 \
-			--pull=newer --manifest dirk1980/${PROJECT}:$TARGET ${WORKDIR}
-
-		if [ $? -eq 0 ]; then BUILD=1; fi
-
-		if [ "$UPLOAD" == "true" ]; then
-			# Push image.
-			podman manifest push --authfile $HOME/.ci/.podman/auth.json \
-				dirk1980/${PROJECT}:$TARGET
-			if [ $? -eq 0 ]; then
-				PUSH=1
-			fi
-
-			# Push stable image as latest on stable build
-			if [ "$TARGET" == "stable" ]; then
-				podman manifest push \
-					--authfile $HOME/.ci/.podman/auth.json \
-					dirk1980/${PROJECT}:stable \
-					docker.io/dirk1980/${PROJECT}:latest
-			fi
-		fi
-
-		# Overall success of the build. - Might be useful for statistics.
-		if [[ $MANIFEST -eq 1 && $BUILD -eq 1 ]]; then
-			SUCCESS=1
-		fi
-
-		# Build the query for the build log database
-		query="insert into buildlog (buildid,project,Type,manifest,"
-		query+="build,push,success) "
-		query+="VALUES ('$BUILD_ID','$PROJECT','$TARGET',$MANIFEST,$BUILD,"
-		query+="$PUSH,$SUCCESS)"
-
-		# Execute the query on the giveb DBFILE
-		sqlite3 "$DBFILE" "$query"
-
-		# Check for error
-		if [ $? -ne 0 ]; then touch $HOME/.ci/bootc/database-failure; fi
-
-		# We are done so remove lock file
-		rm -f $HOME/.ci/${PROJECT}/.$TARGET-running
+# Check if the desired build is already running
+if [ ! -f $HOME/.ci/${PROJECT}/.$TARGET-running ]; then
+	# No build running, so: ABRAKADABRA!
+	if [ ! -d $HOME/.ci/${PROJECT} ]; then
+		mkdir -p $HOME/.ci/${PROJECT}
 	fi
-	# There is a Build already running. Dorry guy, no ABRAKADABRA!
+
+	# Lock the build to avoid concurrent builds of the same type.
+	touch $HOME/.ci/${PROJECT}/.$TARGET-running
+
+	# Remove manifest if it exists
+	podman manifest rm dirk1980/${PROJECT}:$TARGET 2> /dev/null
+
+	# Create the manifest
+	podman manifest create -a dirk1980/${PROJECT}:$TARGET
+	if [ $? -eq 0 ]; then MANIFEST=1; fi
+
+	podman build --build-arg buildid=${BUILD_ID} \
+		--platform linux/amd64,linux/arm64 \
+		--pull=always --manifest dirk1980/${PROJECT}:$TARGET ${WORKDIR}
+
+	if [ $? -eq 0 ]; then BUILD=1; fi
+
+	if [ "$UPLOAD" == "true" ]; then
+		# Push image.
+		podman manifest push --authfile $HOME/.ci/.podman/auth.json \
+			dirk1980/${PROJECT}:$TARGET
+		if [ $? -eq 0 ]; then PUSH=1; fi
+
+		# Push stable image as latest on stable build
+		if [ "$TARGET" == "stable" ]; then
+			podman manifest push \
+				--authfile $HOME/.ci/.podman/auth.json \
+				dirk1980/${PROJECT}:stable \
+				docker.io/dirk1980/${PROJECT}:latest
+		fi
+	fi
+
+	# Overall success of the build. - Might be useful for statistics.
+	if [[ $MANIFEST -eq 1 && $BUILD -eq 1 ]]; then SUCCESS=1; fi
+
+	# Build the query for the build log database
+	query="insert into buildlog (buildid,project,Type,manifest,build,push,success) "
+	query+="VALUES ('$BUILD_ID','$PROJECT','$TARGET',$MANIFEST,$BUILD,$PUSH,$SUCCESS)"
+
+	# Execute the query on the given DBFILE
+	sqlite3 "$DBFILE" "$query"
+
+	# Check for error
+	if [ $? -ne 0 ]; then touch $HOME/.ci/bootc/database-failure; fi
+
+	# We are done so remove lock file
+	rm -f $HOME/.ci/${PROJECT}/.$TARGET-running
 fi
 
 # Reset trap for SIGINT.
-trap SIGINT
+trap "cleanup" INT
